# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1d8b18deea1c0a7739c4a69b7508abad5b5ac13471cb4de90123c1c2a545cbfea768512c89e0a7240d95ba62f6d74e8ec4cfe1966a45ff3d53005729bdd2c09

test:
  secret_key_base: ab42559f0ae962224aa86d58439c79084ca62a7a7f9881aa18d78f5f853215d060f2dee86fac74ec004902b9fd5356119e25ab009c386d7b39195de02d78b359

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
